name: nurminen.io

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |
        docker logout
        echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
        docker image build -t '${{ secrets.DOCKER_USERNAME }}'/nurminen.io .
        docker tag '${{ secrets.DOCKER_USERNAME }}'/nurminen.io '${{ secrets.DOCKER_USERNAME }}'/nurminen.io
        docker push '${{ secrets.DOCKER_USERNAME }}'/nurminen.io